name: sms_command_app
description: A Flutter app to send SMS commands configured remotely from GitHub.
publish_to: 'none'
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  url_launcher: ^6.1.7
  easy_localization: ^3.0.0
  provider: ^6.0.0

flutter:
  uses-material-design: true